build:
  image: docker:19.03.11
  stage: build
  only:
    - tags
  services:
    - docker:19.03.11-dind
  variables:
    IMAGE_TAG: abdelhakverwest/webinar:$CI_COMMIT_TAG
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - export DOCKER_HOST=tcp://localhost:2375
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_TAG}/g" deployment/04-projet-31-dep.yaml
    - kubectl apply -f deployment/
  when: manual
  only:
    - tags
